trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .vscode

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  - group: nuget-account-variables
  - name: imageName
    value: 'aspnetcore-file-validation'

stages:
- stage: Publish_Nuget_Package
  displayName: Publish Nuget Package
  jobs:
  - job: Publish_Nuget_Package
    displayName: Publish Nuget Package
    steps:
    - task: Docker@2
      displayName: Publish Nuget Package with Docker
      inputs:
        command: build
        repository: $(imageName)
        tags: latest
        arguments: >
          --build-arg NUGET_API_KEY=$(NUGET_API_KEY)
